app_settings:
  update_sysctl: true
  install_warp: false

xray_params:
  port: 443
  dest: "amd.com:443" 
  server_names: ["amd.com", "www.amd.com"]
  flow: "xtls-rprx-vision"

remote_server:
  address: "MASTER IP"   
  port: 443              
  uuid: "UUID"
  public_key: "PBK"
  short_id: "SID"
  sni: "amd.com" 

warp:
  enabled: false